INSERT INTO fortune (content) VALUES ('사랑하는 사람을 마음대로 하려고 하지 마세요.')
INSERT INTO fortune (content) VALUES ('새로운 것에 몰두하면 좋은 결과가 있을 것입니다.')
INSERT INTO fortune (content) VALUES ('어떤 삶을 살고 싶은 지 생각해 볼 때 입니다.')
INSERT INTO fortune (content) VALUES ('어려운 것은 시작입니다. 주저하지 마세요.')
INSERT INTO fortune (content) VALUES ('설레는 일이 다가오고 있습니다.')
INSERT INTO fortune (content) VALUES ('예상치 못했던 수입이 들어올 수도 있습니다.')
INSERT INTO fortune (content) VALUES ('다른 사람을 배려하는 만큼 본인에게도 배려가 필요합니다.')
INSERT INTO fortune (content) VALUES ('주위에 친절을 베풀면 당신에게 배로 돌아올 것입니다.')
INSERT INTO fortune (content) VALUES ('잘 이겨낼 수 있을 거예요.')
INSERT INTO fortune (content) VALUES ('당신에게 필요한 것은 적절한 시기를 기다릴 줄 아는 여유입니다.')
INSERT INTO fortune (content) VALUES ('생각지 못한 보물을 발견하게 될 것입니다.')
INSERT INTO fortune (content) VALUES ('미루지 말고 시작해보세요.')